# Lesson 5: Tweaking everything in a plot

library(ggplot2)
library(plyr) # We need the revalue() function from plyr
library(extrafont)
font_import()

filename <- "lesson_5/Encode_HMM_data.txt"
my_data <- read.csv(filename, sep="\t", header=FALSE)
names(my_data)[1:4] <- c("chrom", "start", "stop", "type")

my_data$chrom <- factor(gsub("chr", "", my_data$chrom))
my_data$chrom <- factor(my_data$chrom, levels=c(seq(1,22), "X", "Y"))
my_data <- my_data[my_data$type %in% c("1_Active_Promoter", "4_Strong_Enhancer", "8_Insulator"), ]


my_data$type <- revalue(my_data$type, c("1_Active_Promoter"="Promoter", 
                                        "4_Strong_Enhancer"="Enhancer",
                                        "8_Insulator"="Insulator"))
# Base plot protocol:
ggplot(my_data, aes(x=chrom, fill=type)) + geom_bar()

# How to add a title to plot:
# use labs() [labs ~= labels]
ggplot(my_data, aes(x=chrom, fill=type)) + geom_bar() + labs(title=
                                                               "Regulatory features by chromosome")
# How to change labels of axis and legend
# Note that there's a difference between actually filling up the axis and labelling them.
# ggplot() has parameters that are used to FILL up the plot.
ggplot(my_data, aes(x=chrom, fill=type)) + geom_bar() + labs(title=
                                                               "Regulatory features by chromosome",
                                                             x="Chromosome",
                                                             y="Count",
                                                             fill="Feature")
# A lot of words, so let's store it into a variable!

basic <- ggplot(my_data, aes(x=chrom, fill=type)) + geom_bar() + labs(title=
                                                                        "Regulatory features by chromosome",
                                                                      x="Chromosome",
                                                                      y="Count",
                                                                      fill="Feature")
# Now you can easily add stuff such as a new color

basic + theme_dark()
basic

# You can use theme_set() to establish a theme that will be used for every plot from the execution of the function and onwards
# Note: the default theme is theme_gray()

# - - - - --- -- - - - -     - - -- - - -  - - -

# Color Palettes: 
library(RColorBrewer)
# displays all palettes
display.brewer.all()

# you can use scale_fill_brewer(palette=" ") to easily color
basic + scale_fill_brewer(palette="Set1")
basic + scale_fill_brewer(palette="Pastel1")
basic + scale_fill_brewer(palette="YlOrRd")

basic + scale_fill_manual(values=c("green", "blue", "red"))

chrom_plot <- ggplot(data=my_data, aes(x=type, fill=chrom)) + geom_bar()
chrom_plot

# use brewer.pal() to collect colors from a desired palette
palette1 <- brewer.pal(9, "Set1")
palette2 <- brewer.pal(8, "Set2")
palette3 <- brewer.pal(9, "Set3")

# we can use a pie chart to see all the colors in a palette
pie(rep(1, length(palette1)), col=palette1)
pie(rep(1, length(palette2)), col=palette2)
pie(rep(1, length(palette3)), col=palette3)

# we can stick the palettes together to create one mega vector!
mega_palette <- c(palette1, palette2, palette3)
mega_palette

pie(rep(1, length(mega_palette)), col=mega_palette)
# you can use sample() to make the colors a bit dispersed
chrom_plot + scale_fill_manual(values=sample(mega_palette))

# The set.seed() breaks the fake randomness generated by the computer.
set.seed(1)
chrom_plot + scale_fill_manual(values=sample(mega_palette))

# Font size for everything in the plot

basic + theme_dark(base_family = "Times New Roman")

# For size for everything (separately) in the plot
basic + theme(axis.text=element_text(size=20, family="Times New Roman")) # Numbers on Axis
basic + theme(axis.title=element_text(size=20, family="Times New Roman"))
basic + theme(legend.title=element_text(size=20, family="Times New Roman"))
basic + theme(legend.text=element_text(size=20, family="Times New Roman"))

# Change background color:
basic + theme(panel.background = element_rect(fill="pink"))

# change grid lines

basic + theme(panel.grid.major = element_line(colour = "blue"), panel.grid.minor =
                element_line(colour = "red"))

# Remove all gridlines:
basic + theme(panel.grid.major = element_line(NA),
              panel.grid.minor = element_line(NA))

# Thin black major gridlines on y-axis, the others are removed
basic + theme(panel.grid.major.y = element_line(colour = "black",size=0.2),
              panel.grid.major.x = element_line(NA),
              panel.grid.minor = element_line(NA))

# change tick marks
basic
basic + theme(axis.ticks = element_line(size=1.6))
basic + theme(axis.ticks = element_line(NA))
basic + theme(axis.ticks = element_line(color="blue",size=2))

basic + theme(legend.position = "top")
basic + theme(legend.position = "bottom")
basic + theme(legend.position = c(0,0)) # Bottom Left

# Remove legend title:
basic + labs(fill="")

my_personalized <- basic + scale_fill_manual(values  = c("#f03a37", "#dfa5e8", "#17c90e")) + theme_dark() + 
  theme(axis.ticks.x = element_line(size=1.6, color="red"),
        axis.ticks.y = element_line(size=2, color="#32a8a8"),
        axis.text.x = element_text(color="purple", family="Arial"),
        axis.text.y = element_text(color="#006b2d", family="Georgia"),
        panel.grid.major.y = element_line(color="white"),
        panel.grid.major.x = element_line(color="#84b5b5"),
        plot.title = element_text(hjust=0.5, family="Impact", size=20),
        axis.title.x = element_text(family="Courier New", size=25),
        axis.title.y = element_text(family="Comic Sans MS", size=20),
        legend.background = element_rect(fill = "#9184b5", color="red"),
        legend.text = element_text(color="white"),
        legend.title = element_text(color="#ffcfe4"),
        plot.background = element_rect(fill="#f2c1a0")
                                 )

my_personalized

png("lesson_5/customized_super_cool_plot.png")
my_personalized
dev.off()






